### ISSUE TITLE
Browser will write the element name when you put another element in a element

### ISSUE THREAD

**Issue by mehanalavimajd** [rejectjs/reject#4]
**Describe the bug**
Browser will write the element name when you put another element in a element

**Expected behavior**
```javascript
DIV(
BUTTON("Hello world")
)
```
This will create a button in div but it will write  **Object HtmlbuttonElement**
 
**Screenshots**

**Desktop (please complete the following information):**
 - OS: [windows 10]
 - Browser [chrome]
 - Version [88 ]

**Additional context**

**Comment by mehanalavimajd** [comment]
I have an new idea which can be like this
``` js
DIV(
"<button>hello world</button>"
)
```

**Comment by mehanalavimajd** [comment]
@AshkanLaei and @amirghazi87 what do think about new syntax?👆👆

**Comment by mehanalavimajd** [comment]
Or 
```js
Render(
"
<button>
Hello world
<button/>
"
)
```

**Comment by AshkanLaei** [comment]
> @AshkanLaei and @amirghazi87 what do you think about new syntax?

Learn from RE:DOM

**Comment by mehanalavimajd** [comment]
Why?

**Comment by mehanalavimajd** [comment]
and what do you mean?
